version: '3.9'

services:
  health_checker:
    build: .
    image: health-checker:latest
    depends_on:
      - db

  app:
    build: ./app
    image: app:latest
    ports:
      - "4000:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
